name: Volker on the Grid
favicon: null
layout_spectrum: 0.009598041418939829
typography_spectrum: 0.3106460727285594
title: Work in Progress...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8134964685887098
  lightness: 0.3429986876435578
  saturation: 0.28050699015147984
  rhythmicContrast: 0.5511914601083845
purpose: []
